### ISSUE TITLE
Update data.json with new links

### ISSUE THREAD

**Issue by aidswidjaja** [notseenee/nesappscraper#3]
A maintenance proposal to re-run the scraper and therefore update data.json such that new past papers are included, as of 2022.

I can either run the scraper myself and submit a PR later this week, or if the maintainer of the project would like to go ahead and do this, it would be very much appreciated.

**Comment by notsidney** [comment]
I’d really appreciate you running it and submitting a PR! I haven’t had the time to look into this and am no longer familiar with the Python dependency ecosystem, so I couldn’t even install dependencies when trying to run this.

NESA also updated their website since I last run the scraper, so you may need to modify it if necessary.

**Comment by aidswidjaja** [comment]
Sorry for the delay, admittedly I slightly forgot about this issue after finishing my own HSC.

I've opened a PR (#4) which should have the new data (unfortunately unverified commit because I haven't moved my GPG keys to my new computer, but you can trust it is me :P). I've checked the data quickly and it appears that the most recent links have been grabbed!

I've also made a one-line amendment to an import to fix a depreceation which would have  prevented the scraper from running. Since it's just one line, I've kept it in the same commit.

Feel free to review #4 for feedback and let me know what you think!

**Comment by notsidney** [comment]
Thanks @aidswidjaja! It looks like they’ve updated their website to remove the pages for some old past papers, I think because they updated the curriculum. I’ve added a script to merge the new data that you scraped with the old. It’s live now on https://hscpastpapers.com/
